// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: images.sql

package sqlc

import (
	"context"
)

const getImageByUrl = `-- name: GetImageByUrl :one
SELECT id, type, name, data, url, created_by, created_at, updated_at, deleted_at
FROM images
WHERE url = $1
`

func (q *Queries) GetImageByUrl(ctx context.Context, url string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByUrl, url)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Data,
		&i.Url,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const saveImage = `-- name: SaveImage :one
INSERT INTO images (type, name, data, url, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type, name, data, url, created_by, created_at, updated_at, deleted_at
`

type SaveImageParams struct {
	Type      string `json:"type"`
	Name      string `json:"name"`
	Data      []byte `json:"data"`
	Url       string `json:"url"`
	CreatedBy int32  `json:"created_by"`
}

func (q *Queries) SaveImage(ctx context.Context, arg SaveImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, saveImage,
		arg.Type,
		arg.Name,
		arg.Data,
		arg.Url,
		arg.CreatedBy,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Data,
		&i.Url,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
